---
- hosts: dev
  become: True
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
    - name: Install python pip
      apt:
        name: python3-pip
        state: present

    
    # - name: Install docker
    #   apt:
    #     name: docker
    #     state: present
    # - name: Start Docker service
    #   systemd:
    #     name: docker  
    #     state: started
    #     enabled: yes
    # - name: Install docker-py python module
    #   pip:
    #     name: docker-py
    #     state: present

    # - name: Start the new container
    #   command: "docker run --name {{ container_name }} -d -p 8088:80 pardhuguttula/ansible:{{ DOCKER_TAG }}"

    - name: Run the stop script
      script: ./deploy.sh  # Assuming deploy.sh is in the same directory as the playbook
      ignore_errors: yes
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines

    # - name: Start the new container
    #   docker_container:
    #     name: ansible
    #     image: "pardhuguttula/ansible:{{DOCKER_TAG}}"
    #     state: started
    #     published_ports:
    #       - 0.0.0.0:8088:80